server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name ziii.ddns.net;
    server_tokens off;
    location ^~ /.well-known/acme-challenge/ {
        root /var/www/letsencrypt;
        default_type text/plain;
        try_files $uri =404;
    }
    location / { return 308 https://ziii.ddns.net$request_uri; }
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name ziii.ddns.net;
    server_tokens off;
    ssl_certificate /etc/letsencrypt/live/ziii.ddns.net/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/ziii.ddns.net/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_session_cache shared:ProjectsTLS:10m;
    ssl_session_timeout 1d;
    add_header Strict-Transport-Security "max-age=31536000" always;

    include /etc/nginx/snippets/projects.locations.conf;
}
